trigger:
  - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'OpenMatch.csharp.sln'
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: |
        $(solution)

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: |
        $(solution)
      arguments: -c $(buildConfiguration)

#  - task: VSTest@2
#    inputs:
#      platform: '$(buildPlatform)'
#      configuration: '$(buildConfiguration)'
